// front/drugdashboard_react/src/pages/Header.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

function Header() {
    const navigate = useNavigate();

  return (
    <div style={header_container}>
        <a style={header_title} onClick={() => navigate('/', {replace: true})}>SCDM Drug Search Engine</a>
    </div>
  );
}

const header_container = {
    width: "100%",
    height: "70px",
    backgroundColor: "#009691",
    zIndex: "1",

    display: "flex",
    flexDirection: "row",
    alignItems: "center",
}

const header_title = {
    fontSize: "20px",
    fontWeight: "700",
    textDecoration: "none",
    color: "#FAFAFA",
    cursor: "pointer",
    marginLeft: "30px",
    marginRight: "100px"
}
export default Header;

// frontVue/app/src/components/screen/Header.vue
<template>
    <div id="header-container">

        <a id="header__title" v-on:click="clickHome">SCDM Drug Search Engine</a>

    </div>
</template>

<script>
    function clickHome() {
        const path = '/engine/';
        if(this.$router.currentRoute.path !== path) this.$router.push(path);
    }

    export default {
        methods: {
            clickHome
        }
    };
</script>

<style scoped>
    #header-container {
        width: 100%;
        height: 70px;
        background-color: #009691;
        z-index: 1;

        display: flex;
        flex-direction: row;
        align-items: center;
    }

    #header__title {
        font-size: 20px;
        font-weight: 700;
        text-decoration: none;
        color: #FAFAFA;

        cursor: pointer;

        margin-left: 30px;
        margin-right: 100px;
    }
</style>
